# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: mcferrin
version: '0.0.0'
github: "mcxim/mcferrin"
license: MIT
author: "Maxim Gelfand"
maintainer: "Maxim Gelfand"
# synopsis: implementation of aes encryption in haskell.
# description: implementation of aes encryption in haskell.
# category: Cryptography

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - word8
  - bytestring
  - bytestring-conversion
  - yesod-auth
  - ghc
  - base64-bytestring
  - crypto-api
  - crypto-numbers
  - aeson
  - http-client
  - servant
  - servant-client
  - text
  - utf8-string
  source-dirs: library

executables:
  mcferrin:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - mcferrin
    - bytestring
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  mcferrin-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - mcferrin
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  mcferrin-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - mcferrin
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
