# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: haskell-aes
version: '0.0.0'
github: "mcxim/haskell-aes"
license: MIT
author: "Maxim Gelfand"
maintainer: "Maxim Gelfand"
# synopsis: implementation of aes encryption in haskell.
# description: implementation of aes encryption in haskell.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - word8
  source-dirs: library

executables:
  haskell-aes:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - haskell-aes
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  haskell-aes-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - haskell-aes
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  haskell-aes-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - haskell-aes
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
